# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-ecr-repo" {
  source              = "git@github.com:chanzuckerberg/cztack//aws-ecr-repo?ref=v0.104.2"
  allow_lambda_pull   = local.allow_lambda_pull
  ecr_resource_policy = local.ecr_resource_policy
  force_delete        = local.force_delete
  lifecycle_policy    = local.lifecycle_policy
  max_image_count     = local.max_image_count
  name                = local.name
  read_arns           = local.read_arns
  scan_on_push        = local.scan_on_push
  tag_mutability      = local.tag_mutability
  tags                = local.tags
  write_arns          = local.write_arns



}
