# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "repository_arn" {
  value     = module.aws-ecr-repo.repository_arn
  sensitive = false
}

output "repository_name" {
  value     = module.aws-ecr-repo.repository_name
  sensitive = false
}

output "repository_url" {
  value     = module.aws-ecr-repo.repository_url
  sensitive = false
}


