# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "happy" {
  source               = "../../../modules/happy-env-eks-v4.12.2"
  additional_secrets   = local.additional_secrets
  cloud-env            = local.cloud-env
  ecr_repos            = local.ecr_repos
  eks-cluster          = local.eks-cluster
  github_actions_roles = local.github_actions_roles
  okta_teams           = local.okta_teams
  s3_buckets           = local.s3_buckets
  tags                 = local.tags



}
