name: CypherID Web Infra Deploy
run-name: Deploy CypherID Web Infra to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy'
        required: true
        type: environment
        default: 'debug'
#      profile-name:
#        description: 'The profile name to use for AWS CLI'
#        required: true
#        type: string
#        default: 'idseq-dev'

env:
  AWS_REGION: us-west-2
  #AWS_DEFAULT_OUTPUT: json
  #DEPLOYMENT_ENVIRONMENT: ${{ inputs.environment }}
  TF_CLI_ARGS_apply: "--auto-approve"


permissions:
  id-token: write
  contents: read

jobs:
  DeployTerraform:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - iam-password-policy
          - params-secrets
#          - route53
          - czid-services-private-key
          - cloud-env
#          - idseq-s3-tar-writer
#          - elb-access-logs
          - maintenance
#          - heatmap-optimization
#          - db
#          - downloads
#          - ecs
#          - batch
#          - redis
#          - web
#          - web-waf
#          - auth0
#          - resque
#          - eks
#          - k8s-core
#          - happy
#          - access-management
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/czid-${{ inputs.environment }}-gh-actions-executor
          #role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          aws-profile: idseq-${{ inputs.environment }}
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity --profile idseq-${{ inputs.environment }}
      - name: "Plan - ${{ matrix.component }}"
        run: |
          cd terraform/envs/${{ inputs.environment }}/${{ matrix.component }}/
          make check-plan
#      - name: route53 # Needs Prod credentials for czid-si to configure root DNS
#        run: |
#          cd terraform/envs/${{ inputs.environment }}/route53/
#          make check-plan
#
#          terraform -chdir=cloud-env init
#          terraform -chdir=cloud-env apply
#
#          terraform -chdir=elb-access-logs init
#          terraform -chdir=elb-access-logs apply
#
#          terraform -chdir=maintenance init
#          terraform -chdir=maintenance apply
#
#          terraform -chdir=heatmap-optimization init
#          terraform -chdir=heatmap-optimization apply
#
#          terraform -chdir=db init
#          terraform -chdir=db apply
#
#          terraform -chdir=ecs init
#          terraform -chdir=ecs apply
#
#          terraform -chdir=redis init
#          terraform -chdir=redis apply
#
#          terraform -chdir=web init
#          terraform -chdir=web apply
#
#          terraform -chdir=web-waf init
#          terraform -chdir=web-waf apply
#
#          terraform -chdir=resque init
#          terraform -chdir=resque apply
#
#          terraform -chdir=eks init
#          terraform -chdir=eks apply
#
#          terraform -chdir=k8s-core init
#          terraform -chdir=k8s-core apply
#
#          terraform -chdir=happy init
#          terraform -chdir=happy apply