name: CypherID Web Infra Deploy
run-name: Deploy CypherID Web Infra to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy'
        required: true
        type: environment
        default: 'debug'

env:
  AWS_REGION: us-west-2
  #AWS_DEFAULT_OUTPUT: json
  #DEPLOYMENT_ENVIRONMENT: ${{ inputs.environment }}
  TF_CLI_ARGS_apply: "--auto-approve"


permissions:
  id-token: write
  contents: read

jobs:
  DeployTerraform:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      #max-parallel: 2
      matrix:
        component:
          #- iam-password-policy
          #- params-secrets
          #- route53
          #- czid-services-private-key
          - cloud-env
          #- idseq-s3-tar-writer
          #- elb-access-logs
          - maintenance
          #- heatmap-optimization
          #- db
          #- downloads
          #- ecs
          #- batch
          #- redis
          #- web
          #- web-waf
          #- auth0
          #- resque
          #- eks
          #- k8s-core
          #- happy
          - access-management
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          # TODO: Only uncomment for local execution via nektos-act
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          #output-env-credentials: true
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/czid-${{ inputs.environment }}-gh-actions-executor
          #role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          aws-profile: idseq-${{ inputs.environment }}
      - name: Setup Terraform
        id: setup
        run: |
          make terraform
          .fogg/tfenv/bin/terraform --version
      - name: "Plan - ${{ matrix.component }}"
        id: plan
        # TODO: Handle special cases, like route53 which needs idseq-prod access; or fix route53 to be profile-specific only; also Auth0 Params
        # TODO: make check-plan should be sufficient, but it doesn't leave the plan file after it executes; other commands should also be make commands, but expect AWS CLI
        # make check-auth init fmt refresh check-plan
        run: |
          cd terraform/envs/${{ inputs.environment }}/${{ matrix.component }}/
          ../../../../.fogg/tfenv/bin/terraform init -input=false
          ../../../../.fogg/tfenv/bin/terraform refresh
          set +e
          ../../../../.fogg/tfenv/bin/terraform plan -input=false -detailed-exitcode -refresh=false -out=/tmp/${{ matrix.component }}.plan
          exitcode=$?
          echo "Terraform exited with $exitcode"
          change_count=$(jq -r '.resource_changes[].change.actions[]' /tmp/plan.json | grep -v "no-op" | wc -l)
          echo "count=$change_count" >> "$GITHUB_OUTPUT"
          if [[ $exitcode -eq 2 ]]; then
            exit 0
          else
            exit $exitcode
          fi
      - name: "Summary - ${{ matrix.component }}"
        id: summary
        run: |
          echo "Changes: ${{ matrix.component }} - ${{ steps.plan.outputs.count }}" >> $GITHUB_STEP_SUMMARY
