name: Plan All
run-name: Plan All in ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to which to deploy
        required: true
        type: environment
        default: debug

permissions:
  id-token: write
  contents: read

# NOTE: We would use a matrix, but Outputs are not properly supported yet
jobs:
#  plan-iam-password-policy:
#    name: Plan - iam-password-policy
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: iam-password-policy
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-params-secrets:
#    name: Plan - params-secrets
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: params-secrets
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit

  #plan-route53:
  #  name: Plan - route53
  #  uses: ./.github/workflows/plan_component.yml
  #  with:
  #    environment: ${{ inputs.environment }}
  #    component: route53
  #  permissions:
  #    id-token: write
  #    contents: read
  #  secrets: inherit

  plan-czid-services-private-key:
    name: Plan - czid-services-private-key
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: czid-services-private-key
    permissions:
      id-token: write
      contents: read
    secrets: inherit
#
#  plan-cloud-env:
#    name: Plan - cloud-env
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: cloud-env
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-idseq-s3-tar-writer:
#    name: Plan - idseq-s3-tar-writer
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: idseq-s3-tar-writer
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-elb-access-logs:
#    name: Plan - elb-access-logs
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: elb-access-logs
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-maintenance:
#    name: Plan - maintenance
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: maintenance
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-heatmap-optimization:
#    name: Plan - heatmap-optimization
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: heatmap-optimization
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-db:
#    name: Plan - db
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: db
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-downloads:
#    name: Plan - downloads
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: downloads
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit

  plan-ecs:
    name: Plan - ecs
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: ecs
    permissions:
      id-token: write
      contents: read
    secrets: inherit
#
#  plan-batch:
#    name: Plan - batch
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: batch
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-redis:
#    name: Plan - redis
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: redis
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-web:
#    name: Plan - web
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: web
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-web-waf:
#    name: Plan - web-waf
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: web-waf
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit

  plan-auth0:
    name: Plan - auth0
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: auth0
    permissions:
      id-token: write
      contents: read
    secrets:
      # TODO: inherit should work, but doesn't for some reason
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}

#  plan-resque:
#    name: Plan - resque
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: resque
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-eks:
#    name: Plan - eks
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: eks
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-k8s-core:
#    name: Plan - k8s-core
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: k8s-core
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-happy:
#    name: Plan - happy
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: happy
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit
#
#  plan-access-management:
#    name: Plan - access-management
#    uses: ./.github/workflows/plan_component.yml
#    with:
#      environment: ${{ inputs.environment }}
#      component: access-management
#    permissions:
#      id-token: write
#      contents: read
#    secrets: inherit

  plan-summary:
    name: Plan Summary
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: always() # Run even if upstream jobs fail
    needs:
#      - plan-iam-password-policy
#      - plan-params-secrets
      #- plan-route53
      - plan-czid-services-private-key
#      - plan-cloud-env
#      - plan-idseq-s3-tar-writer
#      - plan-elb-access-logs
#      - plan-maintenance
#      - plan-heatmap-optimization
#      - plan-db
#      - plan-downloads
      - plan-ecs
#      - plan-batch
#      - plan-redis
#      - plan-web
#      - plan-web-waf
      - plan-auth0
#      - plan-resque
#      - plan-eks
#      - plan-k8s-core
#      - plan-happy
#      - plan-access-management
    steps:
      - name: Components Summary
        id: summary
        # TODO: route53, auth0
        run: |
          echo "|| Component | Changes |" >> $GITHUB_STEP_SUMMARY
          echo "| - | --------- | ------- |" >> $GITHUB_STEP_SUMMARY
          
          if [[ ${{ needs.plan-czid-services-private-key.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | czid-services-private-key | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | czid-services-private-key | ${{ needs.plan-czid-services-private-key.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [[ "${{ needs.plan-ecs.outputs.count }}" -eq 0 ]]; then
            echo "| :green_circle: | ecs | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | ecs | ${{ needs.plan-ecs.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [[ -z "${{ needs.plan-auth0.outputs.count }}" ]]; then
            echo "| :red_circle: | auth0 | Failed |" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ needs.plan-auth0.outputs.count }}" -eq 0 ]]; then
            echo "| :green_circle: | auth0 | No Changes |" >> $GITHUB_STEP_SUMMARY 
          else
            echo "| :yellow_circle: | auth0 | ${{ needs.plan-auth0.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
