name: Plan Component
#run-name: Plan - ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Both Github Environment, and the AWS Environment to deploy to"
        type: string
        required: true
      component:
        description: "Fogg Component, located in the terraform/emvs/<environment>/<component> directory"
        type: string
        required: true
    outputs:
      count:
        description: "Number of changes to apply"
        value: ${{ jobs.plan-component.outputs.count }}
      plan:
        description: "The generated Plan artifact"
        value: "${{ jobs.plan-component.outputs.plan }}"

jobs:
  plan-component:
    name: Plan Component
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.plan.outputs.count }}
      plan: "${{ steps.artifact.outputs.plan }}"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Reconfigure Git to use HTTP authentication
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        env:
          AWS_REGION: us-west-2
        with:
          # TODO: Only uncomment for local execution via nektos-act
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          #output-env-credentials: true
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/czid-${{ inputs.environment }}-gh-actions-executor
          #role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          aws-profile: idseq-${{ inputs.environment }}
      - name: Setup Terraform
        id: setup
        run: |
          make terraform
          .fogg/tfenv/bin/terraform --version
      - name: Terraform Plan
        id: plan
        # TODO: Handle special cases, like route53 which needs idseq-prod access; or fix route53 to be profile-specific only; also Auth0 Params
        # NOTE: make check-plan should be sufficient, but it doesn't leave the plan file after it executes; other commands should also be make commands, but expect AWS CLI
        #       make check-auth init fmt refresh check-plan
        run: |
          cd terraform/envs/${{ inputs.environment }}/${{ inputs.component }}/
          ../../../../.fogg/tfenv/bin/terraform init -input=false
          ../../../../.fogg/tfenv/bin/terraform refresh
          echo "Plan will be created in: ${{ github.workspace }}/component-plan"
          set +e
          ../../../../.fogg/tfenv/bin/terraform plan -input=false -detailed-exitcode -refresh=false -out=${{ github.workspace }}/component-plan
          exitcode=$?
          echo "Terraform exited with $exitcode"
          ../../../../.fogg/tfenv/bin/terraform show -json ${{ github.workspace }}/component-plan > plan.json
          change_count=$(jq -r '.resource_changes[].change.actions[]' plan.json | grep -v "no-op" | wc -l)
          echo "count=$change_count" >> "$GITHUB_OUTPUT"
          echo "Plan is located in: ${{ github.workspace }}"
          ls ${{ github.workspace }
          if [[ $exitcode -eq 2 ]]; then
            exit 0
          else
            exit $exitcode
          fi
      # TODO: Only uncomment for local execution via nektos-act, when testing outputs and artifacts
      #- name: Terraform Plan
      #  id: plan
      #  run: |
      #    echo "{}" > ./component.plan
      #    count=$(( RANDOM % 3 ))
      #    echo "count=$count" >> "$GITHUB_OUTPUT"
      - name: Upload Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ inputs.component }}
          path: ${{ github.workspace }}/component-plan
          retention-days: 1
          compression-level: 0 # Plan files are already pretty compact, and max compression gives at best 10% savings
          if-no-files-found: error
      - name: Artifact Output
        id: artifact
        run: |
          echo "plan=plan-${{ inputs.component }}" >> "$GITHUB_OUTPUT"
