name: Plan All
run-name: Plan All in ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to which to deploy
        required: true
        type: environment
        default: debug

permissions:
  id-token: write
  contents: read

# NOTE: We would use a matrix, but Outputs are not properly supported yet
jobs:
  plan-iam-password-policy:
    name: Plan - iam-password-policy
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: iam-password-policy
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-params-secrets:
    name: Plan - params-secrets
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: params-secrets
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  #plan-route53:
  #  name: Plan - route53
  #  uses: ./.github/workflows/plan_component.yml
  #  with:
  #    environment: ${{ inputs.environment }}
  #    component: route53
  #  permissions:
  #    id-token: write
  #    contents: read
  #  secrets: inherit

  plan-czid-services-private-key:
    name: Plan - czid-services-private-key
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: czid-services-private-key
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-cloud-env:
    name: Plan - cloud-env
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: cloud-env
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-idseq-s3-tar-writer:
    name: Plan - idseq-s3-tar-writer
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: idseq-s3-tar-writer
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-elb-access-logs:
    name: Plan - elb-access-logs
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: elb-access-logs
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-maintenance:
    name: Plan - maintenance
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: maintenance
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-heatmap-optimization:
    name: Plan - heatmap-optimization
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: heatmap-optimization
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-db:
    name: Plan - db
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: db
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-downloads:
    name: Plan - downloads
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: downloads
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-ecs:
    name: Plan - ecs
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: ecs
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-batch:
    name: Plan - batch
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: batch
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-redis:
    name: Plan - redis
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: redis
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-web:
    name: Plan - web
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: web
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-web-waf:
    name: Plan - web-waf
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: web-waf
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-auth0:
    name: Plan - auth0
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: auth0
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-resque:
    name: Plan - resque
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: resque
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-eks:
    name: Plan - eks
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: eks
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-k8s-core:
    name: Plan - k8s-core
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: k8s-core
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-happy:
    name: Plan - happy
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: happy
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-access-management:
    name: Plan - access-management
    uses: ./.github/workflows/plan_component.yml
    with:
      environment: ${{ inputs.environment }}
      component: access-management
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  plan-summary:
    name: Plan Summary
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs:
      - plan-iam-password-policy
      - plan-params-secrets
      #- plan-route53
      - plan-czid-services-private-key
      - plan-cloud-env
      - plan-idseq-s3-tar-writer
      - plan-elb-access-logs
      - plan-maintenance
      - plan-heatmap-optimization
      - plan-db
      - plan-downloads
      - plan-ecs
      - plan-batch
      - plan-redis
      - plan-web
      - plan-web-waf
      - plan-auth0
      - plan-resque
      - plan-eks
      - plan-k8s-core
      - plan-happy
      - plan-access-management
    steps:
      - name: Components Summary
        id: summary
        # TODO: route53, auth0
        run: |
          echo "| * | Component | Changes |" >> $GITHUB_STEP_SUMMARY
          echo "| - | --------- | ------- |" >> $GITHUB_STEP_SUMMARY
          if [[ ${{ needs.plan-iam-password-policy.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | iam-password-policy | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | iam-password-policy | ${{ needs.plan-iam-password-policy.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-params-secrets.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | params-secrets | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | params-secrets | ${{ needs.plan-params-secrets.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-czid-services-private-key.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | czid-services-private-key | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | czid-services-private-key | ${{ needs.plan-czid-services-private-key.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-cloud-env.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | cloud-env | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | cloud-env | ${{ needs.plan-cloud-env.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-idseq-s3-tar-writer.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | idseq-s3-tar-writer | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | idseq-s3-tar-writer | ${{ needs.plan-idseq-s3-tar-writer.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-elb-access-logs.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | elb-access-logs | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | elb-access-logs | ${{ needs.plan-elb-access-logs.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-maintenance.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | maintenance | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | maintenance | ${{ needs.plan-maintenance.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-heatmap-optimization.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | heatmap-optimization | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | heatmap-optimization | ${{ needs.plan-heatmap-optimization.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-db.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | db | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | db | ${{ needs.plan-db.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-downloads.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | downloads | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | downloads | ${{ needs.plan-downloads.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-ecs.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | ecs | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | ecs | ${{ needs.plan-ecs.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-batch.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | batch | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | batch | ${{ needs.plan-batch.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-redis.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | redis | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | redis | ${{ needs.plan-redis.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-web.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | web | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | web | ${{ needs.plan-web.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-web-waf.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | web-waf | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | web-waf | ${{ needs.plan-web-waf.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-resque.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | resque | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | resque | ${{ needs.plan-resque.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-auth0.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | auth0 | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | auth0 | ${{ needs.plan-auth0.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-eks.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | eks | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | eks | ${{ needs.plan-eks.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-k8s-core.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | k8s-core | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | k8s-core | ${{ needs.plan-k8s-core.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-happy.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | happy | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | happy | ${{ needs.plan-happy.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${{ needs.plan-access-management.outputs.count }} -eq 0 ]]; then
            echo "| :green_circle: | access-management | No Changes |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| :yellow_circle: | access-management | ${{ needs.plan-access-management.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          fi
